services:
  dphe-data-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: dphe-data-api:latest
    environment:
      DB_PATH: ${DB_PATH:-./test/resources/deepphe.sqlite3}
      NODE_ENV: ${NODE_ENV:-production}
      PORT: ${PORT:-3333}
    ports:
      - "${PORT:-3333}:${PORT:-3333}"
    restart: unless-stopped
